<a href="https://colab.research.google.com/github/sheezarainbow9/Notebooks/blob/main/aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sheeza Adrian da Silva.
Aula 1 - NumPy.

Importando o NumPy:

In [89]:
import numpy as np

Criando uma lista:

In [90]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

Transformando essa lista em um Array Numpy:

In [91]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Uma forma mais simples de criarmos essa lista:

In [92]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

Transformando agora essa lista em um Array Numpy:

In [93]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

arange: Fazendo as etapas anteriores numa única sintaxe:

In [94]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Start, stop, step:

In [95]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Arredondando os valores obtidos:

In [96]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

Também podemos 'forçar' o tipo dos elementos:

In [97]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Também podemos pré determinar o tipo dos elementos:

In [98]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Acima teremos os números inteiros, mas posso deixar meu array previamente preparado  para trabalhar futuramente com tipos float ( . ):

In [99]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Verificando o tipo do objeto:

In [100]:
type(array4)

numpy.ndarray

Verificando o tipo dos elementos do array:

In [101]:
array4.dtype  # ou print(array4.dtype)

dtype('float64')

Também podemos criar um array digitando os valores:

In [102]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


Selecionando um elemento específico:

In [103]:
vetor1[3]

3

Selecionando um intervalo específico:

In [104]:
vetor1[0:2]

array([0, 1])

Ou também:

In [105]:
print(vetor1[0:2])

[0 1]


Criando um array de strings:

In [106]:
s = np.array(['Python', 'Profissional', 'Java', "Água"])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [107]:
s = np.array(['Python', 1464321315, 'Profissional', 'Java', "Água"])
s

array(['Python', '1464321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

Alterando um elemento do Array:

In [108]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

Vamos tentar incluir elementos:

In [109]:
vetor1[0] = 'Novo elemento'
vetor1

ValueError: ignored

Agora tente o seguinte:

In [110]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

Criando a 1a Matriz:

In [111]:
minhaMatriz = np.array([[1, 2, 3],
                        [4, 5, 6]])

Lembrando que você pode escrever apenas assim:

In [112]:
minhaMatriz = np.array([[1, 2, 3], [4, 5, 6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

Podemos criar uma matriz a partir de uma lista:

In [113]:
minhaLista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]

Agora usaremos np.matrix:

In [114]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

np.zeros: pode formar vetores e matrizes:

In [115]:
# Vetor:
x = np.zeros(3)
x

array([0., 0., 0.])

In [116]:
# Matriz:
x = np.zeros((3, 2))  # 3 - linhas, 2 - colunas.
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Outra forma: sem armazenar em variáveis:

In [ ]:
# Vetor:
print(np.zeros(3))

In [ ]:
# Matriz:
print(np.zeros((3, 2)))

np.ones:

In [ ]:
x = np.ones((5, 3)) 
x

Igualmente, é possível para apenas um vetor:

In [ ]:
y = np.ones(5)
y

**Desafio**: Como obter uma matriz 4x4 apenas com números 8?

In [ ]:
m = np.ones((4, 4)) * 8
m

np.diag para formar matrizes:

Os valores passados como parâmetro formam uma diagonal:

In [ ]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

np.eye para formar matrizes:

In [ ]:
y = np.eye(5)
y

Agora, determinando o tipo int:

In [ ]:
y = np.eye(5, dtype=int)
y

Verificando o shape (forma) de duas maneiras:

In [ ]:
np.shape(minhaMatriz)

In [ ]:
# Ou:
minhaMatriz.shape

Verificando o tipo da matriz:

In [ ]:
type(minhaMatriz)

Verificando o tipo dos dados da matriz:

In [ ]:
minhaMatriz.dtype

Selecionando elementos de uma matriz:

In [ ]:
minhaMatriz[2, 1]

Selecionando a primeira linha de uma matriz:

In [ ]:
print(minhaMatriz[0, :])

Selecionando a terceira coluna de uma matriz:

In [ ]:
print(minhaMatriz[:, 2])

Alterando um elemento da matriz:

In [ ]:
minhaMatriz[1, 0] = 100
minhaMatriz

Obtendo soma dos valores do array:

In [ ]:
meuArray

In [ ]:
np.sum(meuArray)

Obtendo produto:

In [ ]:
np.prod(meuArray)

Obtendo a **soma acumulada**:

In [ ]:
np.cumsum(meuArray)

Obtendo o **valor mínimo** do array:

In [ ]:
meuArray.min()

Obtendo o **valor máximo** do array:

In [ ]:
meuArray.max()

Obtendo **média** dos valores do Array:

In [ ]:
np.mean(meuArray)

Obtendo **mediana** dos valores do Array:

In [ ]:
np.median(meuArray)

Obtendo a **variância** (variação do valor para a média) dos valores do Array:

In [ ]:
np.var(meuArray)

Obtendo o **desvio padrão** dos valores do Array:

In [ ]:
np.std(meuArray)

Desafio de classe:

1 - Criar um array unidimensional usando arange com 20 elementos;

2 - 'Varrer' o array para obter os pares;

3 - Obter a média, soma, produto, variância e o desvio padrão do array;

4 - Saber se os valores são maiores que 5;

5 - Obter os valores maiores que 5;

In [128]:
# 1:
array2 = np.arange(21)
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [129]:
# 2:
par = array2[::2]
print(f'Números pares: {par}')


Números pares: [ 0  2  4  6  8 10 12 14 16 18 20]


In [130]:
# 3:
impar = array2[1::2]
print(f'Números ímpares: {impar}')

Números ímpares: [ 1  3  5  7  9 11 13 15 17 19]


In [131]:
# 4:
media = np.mean(array2)
print(f'Média: {media}')

soma = np.sum(array2)
print(f'Soma: {soma}')

produto = np.prod(array2)
print(f'Produto: {produto}')

var = np.var(array2)
print(f'Variância: {var}')

des_padrao = np.mean(array2)
print(f'Desvio Padrão: {des_padrao}')

Média: 10.0
Soma: 210
Produto: 0
Variância: 36.666666666666664
Desvio Padrão: 10.0


In [132]:
# 4:
array2 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [133]:
# 5:
maior = array2[array2 > 5]
print(f'Números maiores que 5: {maior}')

Números maiores que 5: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
