<a href="https://colab.research.google.com/github/sheezarainbow9/Notebooks/blob/main/Sheeza_Aula0202DataSci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

DataFrame: Sua formação é semelhante à formação de uma serie, com o acréscimo de colunas, já que 'df' é uma tabela. Constitui-se assim:

df = pd.DataFrame(data, index, columns)

Uma matriz tabela, ou simplesmente matriz, pode ser convertida em um DataFrame.

Vamos relembrar como criar uma matriz manualmente:

In [ ]:
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]]

In [ ]:
type(data)

list

Agora vamos passar essa atribuição como parâmetro:

In [ ]:
dados = np.matrix(data)
dados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Outra forma de criar a matriz:

In [ ]:
meusDados = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Transformar a matriz em um DataFrame:

In [ ]:
pd.DataFrame(meusDados)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Este resultado se dará porque não salvamos o DataFrame em uma variável:

In [ ]:
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Vamos repetir a operação:

In [ ]:
pd.DataFrame(meusDados)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Agora armazenando o resultado numa variável:

In [ ]:
meuDf = pd.DataFrame(meusDados)

In [ ]:
type(meuDf)

pandas.core.frame.DataFrame

Verificar os tipos dos dados do nosso Data Frame:

In [ ]:
meuDf.dtypes

0    int64
1    int64
2    int64
dtype: object

Para vermos mais informações de todo o Data Frame de forma simples, temos o .info():

In [ ]:
meuDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      int64
 1   1       4 non-null      int64
 2   2       4 non-null      int64
dtypes: int64(3)
memory usage: 224.0 bytes


Modificando o tipo das variáveis com astype(). É comum precisarmos modificar o tipo de dados para trabalhar com eles:

In [ ]:
meuDf.astype(float)

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

Porém, ao digitarmos novamente 'meuDf', ela volta ao formato original:

In [ ]:
meuDf

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

Temos que armazenar a nova informação em uma variável:

In [ ]:
meuDf = meuDf.astype(float)
meuDf

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

Modificando o tipo das variáveis com astype():

In [ ]:
meuDf[1] = meuDf[1].astype(str)
meuDf

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [ ]:
meuDf.dtypes

0    float64
1     object
2    float64
dtype: object

Um dos primeiros comandos que usamos imediatamente após carregarmos nosso DataFrame costuma ser o shape. Em seguida é comum usar o head, para sabermos como está visualmente nosso DF. Por padrão, ele mostra as 5 primeiras linhas, mas podemos ver outras linhas diferentes pondo um valor entre parênteses: 

In [ ]:
meuDf.shape

(4, 3)

In [ ]:
meuDf.head()

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [ ]:
meuDf.head(2)

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

Semelhante ao head, o tail serve para verificarmos as últimas linhas do DF. Tem por padrão mostrar as 5 últimas linhas, podendo modificar isto com valor entre parênteses para mostrar mais:

In [ ]:
meuDf.tail()

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [ ]:
meuDf.tail(2)

0     1     2
2   7.0   8.0   9.0
3  10.0  11.0  12.0

Resumo estatístico:

Aqui, como temos colunas de string (a 1), ele as ignora.

In [ ]:
meuDf.describe()

0          2
count   4.000000   4.000000
mean    5.500000   7.500000
std     3.872983   3.872983
min     1.000000   3.000000
25%     3.250000   5.250000
50%     5.500000   7.500000
75%     7.750000   9.750000
max    10.000000  12.000000

Deixando o DF mais organizado:

In [ ]:
indice = ['Linha ' + str(i) for i in range(4)]

In [ ]:
colunas = ['Coluna ' + str(i) for i in range(3)]

Abreviando:

In [ ]:
df2 = pd.DataFrame(meusDados, indice, colunas)
df2

Coluna 0  Coluna 1  Coluna 2
Linha 0         1         2         3
Linha 1         4         5         6
Linha 2         7         8         9
Linha 3        10        11        12

Não é intuitivo, mas é possível criar um DF manualmente:

In [ ]:
df3 = {'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
       'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
       'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}
      } 

In [ ]:
df3 = pd.DataFrame(df3)
df3

Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

Concatenando:

In [ ]:
df4 = pd.concat([meuDf, df2, df3])
df4

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0   5.0   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0   8.0   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0  11.0  12.0       NaN       NaN       NaN      NaN      NaN   
Linha 0   NaN   NaN   NaN       1.0       2.0       3.0      NaN      NaN   
Linha 1   NaN   NaN   NaN       4.0       5.0       6.0      NaN      NaN   
Linha 2   NaN   NaN   NaN       7.0       8.0       9.0      NaN      NaN   
Linha 3   NaN   NaN   NaN      10.0      11.0      12.0      NaN      NaN   
Linha0    NaN   NaN   NaN       NaN       NaN       NaN      1.0      2.0   
Linha1    NaN   NaN   NaN       NaN       NaN       NaN      4.0      5.0   
Linha2    NaN   NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         Coluna2  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
Linha 0      NaN  
Linha 1      NaN  
Linha 2      NaN  
Linha 3      NaN  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

Tratamento dos dados: algumas vezes será fundamental substituir valores NaN pela média, mediana, etc, ou excluí-los. Outras vezes pode ser perigoso.

Mostrar os valores nulos:

In [ ]:
df4.isnull()

0      1      2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0        False  False  False      True      True      True     True     True   
1        False  False  False      True      True      True     True     True   
2        False  False  False      True      True      True     True     True   
3        False  False  False      True      True      True     True     True   
Linha 0   True   True   True     False     False     False     True     True   
Linha 1   True   True   True     False     False     False     True     True   
Linha 2   True   True   True     False     False     False     True     True   
Linha 3   True   True   True     False     False     False     True     True   
Linha0    True   True   True      True      True      True    False    False   
Linha1    True   True   True      True      True      True    False    False   
Linha2    True   True   True      True      True      True    False    False   

         Coluna2  
0           True  
1           True  
2           True  
3           True  
Linha 0     True  
Linha 1     True  
Linha 2     True  
Linha 3     True  
Linha0     False  
Linha1     False  
Linha2     False

Somatório dos nulos:

In [ ]:
df4.isnull().sum()

0           7
1           7
2           7
Coluna 0    7
Coluna 1    7
Coluna 2    7
Coluna0     8
Coluna1     8
Coluna2     8
dtype: int64

Total geral de nulos:

In [ ]:
df4.isnull().sum().sum()

66

Filtrar Not A number: fillna. Filtra os valores not a number:

In [ ]:
df4.fillna

<bound method DataFrame.fillna of             0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0   5.0   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0   8.0   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0  11.0  12.0       NaN       NaN       NaN      NaN      NaN   
Linha 0   NaN   NaN   NaN       1.0       2.0       3.0      NaN      NaN   
Linha 1   NaN   NaN   NaN       4.0       5.0       6.0      NaN      NaN   
Linha 2   NaN   NaN   NaN       7.0       8.0       9.0      NaN      NaN   
Linha 3   NaN   NaN   NaN      10.0      11.0      12.0      NaN      NaN   
Linha0    NaN   NaN   NaN       NaN       NaN       NaN      1.0      2.0   
Linha1    NaN   NaN   NaN       NaN       NaN       NaN      4.0      5.0   
Linha2    NaN   NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         Coluna2  
0            NaN  
1  

Substituindo todos os valores NaN do nosso DF pela média dos valores válidos das colunas:

In [ ]:
df5 = df4.fillna(df4.mean())
df5

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   NaN   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   NaN   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   NaN   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   NaN   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   NaN   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   NaN   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   NaN   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

dropna: é um 'último recurso', quando não foi possível tratar os valores NaN ou o tratamento mais prejudicava do que ajudava. Antes de usá-lo, faça a CÓPIA DO DF:

In [ ]:
df8 = df5.copy()

O dropna significa que o Pandas deletou os NaN onde eles eram True:

In [ ]:
df4.dropna(inplace = True)
df4

Empty DataFrame
Columns: [0, 1, 2, Coluna 0, Coluna 1, Coluna 2, Coluna0, Coluna1, Coluna2]
Index: []

Agora que perdemos nosso df4, vamos relembrar quem é o nosso DF 5:

In [ ]:
df5

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   NaN   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   NaN   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   NaN   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   NaN   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5   NaN   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5   NaN   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   NaN   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

O que aconteceu com a coluna 1? Neste caso vamos optar por deletar esses valores (que levarão com ele suas informações correlatas):

In [ ]:
df5.dropna(subset = [1], inplace = True)
df5

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  Coluna2
0   1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0      6.0
1   4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0      6.0
2   7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0      6.0
3  10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0      6.0

Drop: excluir colunas (ou linhas) para reduzirmos nosos DF e deixá-lo mais 'limpo':

In [ ]:
df6 = df5.drop(columns = ['Coluna0'])
df6

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna1  Coluna2
0   1.0   2.0   3.0       5.5       6.5       7.5      5.0      6.0
1   4.0   5.0   6.0       5.5       6.5       7.5      5.0      6.0
2   7.0   8.0   9.0       5.5       6.5       7.5      5.0      6.0
3  10.0  11.0  12.0       5.5       6.5       7.5      5.0      6.0

In [ ]:
df7 = df6.drop(index = [2])
df7

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna1  Coluna2
0   1.0   2.0   3.0       5.5       6.5       7.5      5.0      6.0
1   4.0   5.0   6.0       5.5       6.5       7.5      5.0      6.0
3  10.0  11.0  12.0       5.5       6.5       7.5      5.0      6.0

Saber quais os valores únicos em uma coluna:

In [ ]:
df5.Coluna2.unique()

array([6.])

Podemos usá-lo para saber as colunas ou o índice do nosso DF:

In [ ]:
df5.columns.unique()

Index([0, 1, 2, 'Coluna 0', 'Coluna 1', 'Coluna 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')

In [ ]:
df5.index.unique()

Index([0, 1, 2, 3], dtype='object')

Ordenando por:

In [ ]:
df8.sort_values(by = 'Coluna1')

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
Linha0    5.5   NaN   7.5       5.5       6.5       7.5      1.0      2.0   
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5   NaN   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5   NaN   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5   NaN   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5   NaN   7.5      10.0      11.0      12.0      4.0      5.0   
Linha1    5.5   NaN   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5   NaN   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
Linha0       3.0  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha1       6.0  
Linha2       9.0

Renomeando colunas e linhas:

In [ ]:
df8.rename(columns = {'Coluna1': 'COLUNA 1'}, inplace = True)
df8

0     1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  COLUNA 1  \
0         1.0   2.0   3.0       5.5       6.5       7.5      4.0       5.0   
1         4.0   5.0   6.0       5.5       6.5       7.5      4.0       5.0   
2         7.0   8.0   9.0       5.5       6.5       7.5      4.0       5.0   
3        10.0  11.0  12.0       5.5       6.5       7.5      4.0       5.0   
Linha 0   5.5   NaN   7.5       1.0       2.0       3.0      4.0       5.0   
Linha 1   5.5   NaN   7.5       4.0       5.0       6.0      4.0       5.0   
Linha 2   5.5   NaN   7.5       7.0       8.0       9.0      4.0       5.0   
Linha 3   5.5   NaN   7.5      10.0      11.0      12.0      4.0       5.0   
Linha0    5.5   NaN   7.5       5.5       6.5       7.5      1.0       2.0   
Linha1    5.5   NaN   7.5       5.5       6.5       7.5      4.0       5.0   
Linha2    5.5   NaN   7.5       5.5       6.5       7.5      7.0       8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

Renomeando colunas e linhas (index) com df.rename():

In [ ]:
df8.rename(columns = {0: 'janeiro', 1: 'fevereiro', 2: 'marco', 'Coluna 0': 'abril',
                      'Coluna 1': 'maio', 'Coluna 2': 'junho', 'Coluna0': 'julho',
                      'COLUNA 1': 'agosto', 'Coluna2': 'setembro'}, inplace = True)

df8

janeiro fevereiro  marco  abril  maio  junho  julho  agosto  setembro
0            1.0       2.0    3.0    5.5   6.5    7.5    4.0     5.0       6.0
1            4.0       5.0    6.0    5.5   6.5    7.5    4.0     5.0       6.0
2            7.0       8.0    9.0    5.5   6.5    7.5    4.0     5.0       6.0
3           10.0      11.0   12.0    5.5   6.5    7.5    4.0     5.0       6.0
Linha 0      5.5       NaN    7.5    1.0   2.0    3.0    4.0     5.0       6.0
Linha 1      5.5       NaN    7.5    4.0   5.0    6.0    4.0     5.0       6.0
Linha 2      5.5       NaN    7.5    7.0   8.0    9.0    4.0     5.0       6.0
Linha 3      5.5       NaN    7.5   10.0  11.0   12.0    4.0     5.0       6.0
Linha0       5.5       NaN    7.5    5.5   6.5    7.5    1.0     2.0       3.0
Linha1       5.5       NaN    7.5    5.5   6.5    7.5    4.0     5.0       6.0
Linha2       5.5       NaN    7.5    5.5   6.5    7.5    7.0     8.0       9.0

Renomeando as linhas: Como sobraram uns NaN, deletaremos eles antes:

In [ ]:
df8.dropna(subset = ['fevereiro'], inplace = True)
df8

janeiro fevereiro  marco  abril  maio  junho  julho  agosto  setembro
0      1.0       2.0    3.0    5.5   6.5    7.5    4.0     5.0       6.0
1      4.0       5.0    6.0    5.5   6.5    7.5    4.0     5.0       6.0
2      7.0       8.0    9.0    5.5   6.5    7.5    4.0     5.0       6.0
3     10.0      11.0   12.0    5.5   6.5    7.5    4.0     5.0       6.0

In [ ]:
df9 = df8.rename(index = {0: 'Elon Musk', 1: 'Bill Gates',
                           2: 'Bernard Arnault', 3: 'Mark zuckerberg'})

df9

janeiro fevereiro  marco  abril  maio  junho  julho  agosto  \
Elon Musk            1.0       2.0    3.0    5.5   6.5    7.5    4.0     5.0   
Bill Gates           4.0       5.0    6.0    5.5   6.5    7.5    4.0     5.0   
Bernard Arnault      7.0       8.0    9.0    5.5   6.5    7.5    4.0     5.0   
Mark zuckerberg     10.0      11.0   12.0    5.5   6.5    7.5    4.0     5.0   

                 setembro  
Elon Musk             6.0  
Bill Gates            6.0  
Bernard Arnault       6.0  
Mark zuckerberg       6.0

Reiniciando o index com reset_index():

In [ ]:
df8.reset_index()

index  janeiro fevereiro  marco  abril  maio  junho  julho  agosto  \
0      0      1.0       2.0    3.0    5.5   6.5    7.5    4.0     5.0   
1      1      4.0       5.0    6.0    5.5   6.5    7.5    4.0     5.0   
2      2      7.0       8.0    9.0    5.5   6.5    7.5    4.0     5.0   
3      3     10.0      11.0   12.0    5.5   6.5    7.5    4.0     5.0   

   setembro  
0       6.0  
1       6.0  
2       6.0  
3       6.0

Contando valores:

In [ ]:
df8.value_counts('marco')

marco
3.0     1
6.0     1
9.0     1
12.0    1
dtype: int64

Para obter o total de colunas:

In [ ]:
df8.columns.value_counts().sum()

9

Contar o total de linhas:

In [ ]:
df8.index.value_counts().sum()

4