In [1]:
import numpy as np

In [2]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

# Transformando a lista num Array NumPy

In [3]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Fazendo as etapas anteriores com uma sintaxe:

In [6]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Start, stop, step:

In [7]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Arredondando os valores obtidos:

In [8]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

Podemos 'forçar' o tipo dos elementos:

In [9]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Podemos pré determinar o tipo dos elementos:

In [11]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Tipo de objeto:

In [12]:
type(array4)

numpy.ndarray

Tipo dos elementos do array:

In [13]:
array4.dtype

dtype('int64')

Criar arrays digitando seus valores:

In [14]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


Selecionando elemento específico:

In [15]:
vetor1[3]

3

Selecionando intervalo específico:

In [16]:
vetor1[0:2] # ou : print(vetor1[0:2])

array([0, 1])

Alterando um elemento do array:

In [18]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

Tentar incluir elementos:

In [20]:
# vetor1[0] = 'Novo elemento'
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

Criando 1a matriz:

In [22]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6]])
matriz1

array([[1, 2, 3],
       [4, 5, 6]])

Criar matriz a partir de uma lista:

In [58]:
minhaLista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]

Agora usaremos np.matrix:

In [59]:
matriz2 = np.matrix(minhaLista)
matriz2

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

np.zeros: pode formar vetores e matrizes:

In [30]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [31]:
x = np.zeros((3, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Sem armazenar em variáveis:

In [32]:
print(np.zeros(3))

[0. 0. 0.]


np.ones:

In [33]:
x = np.ones((5, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Para apenas um vetor:

In [34]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

Desafio: como obter uma matriz 4x4 apenas com números 8?

In [ ]:
m = np.ones((4,4)) * 8
m

np.diag para formar matrizes: Valores passados como parâmetro formam uma diagonal:

In [53]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

np.eye para formar matrizes:

In [55]:
y = np.eye(5)
5

5

agora, determinando o tipo  int:

In [56]:
y = np.eye(5, dtype = int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Verificando o shape (forma) de 2 maneiras:

In [60]:
np.shape(matriz2) # ou matriz2.shape

(3, 3)

Verificando o tipo da matriz:

In [61]:
type(matriz2)

numpy.matrix

Verificando o tipo de dados da matriz:

In [62]:
matriz2.dtype

dtype('int64')

Selecionando elementos de uma matriz:

In [63]:
matriz2[2, 1]

48

Selecionando a 1a linha de uma matriz:

In [64]:
print(matriz2[0,:])

[[13 81 22]]


Selecionando a 3a coluna de uma matriz:

In [65]:
print(matriz2[:,2])

[[22]
 [59]
 [94]]


Alterando um elemento da matriz:

In [66]:
matriz2[1, 0] = 100
matriz2

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

Operações básicas: Soma dos valores do array:

In [67]:
np.sum(meuArray)

36

Obtendo o produto:

In [68]:
np.prod(meuArray)

0

Soma acumulada:

In [69]:
np.cumsum(meuArray)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

Obtendo o valor mínimo do array:

In [71]:
meuArray.min()

0

Obtendo o valor máximo do array:

In [72]:
meuArray.max()

8

Média dos valores do array:

In [73]:
np.mean(meuArray)

4.0

Mediana:

In [74]:
np.median(meuArray)

4.0

Variância dos valores:

In [75]:
np.var(meuArray)

6.666666666666667

Desvio padrão dos valores:

In [76]:
np.std(meuArray)

2.581988897471611

Desafio de classe: 
Criar array unidimensional usando arange com 20 elementos:

In [79]:
meu_array = np.arange(20)
meu_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Desafio de classe: 
Obter a média, soma, variância e desvio padrão:

In [87]:
np.mean(meu_array)
np.std(meu_array)
np.var(meu_array)
np.sum(meu_array)
np.prod(meu_array)

0

Desafio de classe: Varrer o array para obter os pares:

In [84]:
meu_array[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Desafio de classe: Varrer o array para obter os ímpares:

In [85]:
meu_array[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Desafio de classe: Saber se os valores são maiores que 5:

In [88]:
meu_array > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

Desafio de classe: Obter valores maiores que 5:

In [89]:
meu_array [meu_array > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])